### ISSUE TITLE
Not all meta fields in _source print a nice error

### ISSUE THREAD

**Issue by vagnerclementino** [vagnerclementino/elasticsearch#50]
Given this example:

```json
POST /_bulk
{"index":{"_index":"releaseindex","_type":"rootobject","_id":"1"}}
{"product": [{"_version": 14}],"seo": {"section": [{"_version": 1}]},"_version": 1}
{"index":{"_index":"releaseindex","_type":"rootobject","_id":"2"}}
{"seo": {"section": [{"_version": 1}]},"_version": 1}
{"index":{"_index":"releaseindex","_type":"rootobject","_id":"3"}}
{"_version": 1}
{"index":{"_index":"releaseindex","_type":"rootobject","_id":"4"}}
{"product": [{"_version": 14}],"seo": {"section": [{"_version": 1}]}}
{"index":{"_index":"releaseindex","_type":"rootobject","_id":"5"}}
{"_field_names": 1}
{"index":{"_index":"releaseindex","_type":"rootobject","_id":"5"}}
{"_index": 1}
```

We get different messages for adding meta fields in the root of `_source` e.g look at `_index` vs `_field_names`

```json
{
      "index": {
        "_index": "releaseindex",
        "_type": "rootobject",
        "_id": "5",
        "status": 400,
        "error": {
          "type": "illegal_argument_exception",
          "reason": "Field [_field_names] is defined twice in [rootobject]"
        }
      }
    },
    {
      "index": {
        "_index": "releaseindex",
        "_type": "rootobject",
        "_id": "5",
        "status": 400,
        "error": {
          "type": "mapper_parsing_exception",
          "reason": "Field [_index] is a metadata field and cannot be added inside a document. Use the index API request parameters."
        }
      }
```

**Comment by issuequality** [comment]
Dear @vagnerclementino,
These issue do not looks great :-1:
 Would you like us to help you improve it? :smile:
You could take the following action:
 - [ ] Add step to reproduce.
 - [ ] To Attach files with a screenshots or stacktraces.
 - [ ] To include a code block.
 - [ ] To improve the readability of the text.



**Did you know:**
* Issues containing *stack traces* get fixed sooner.
* Issues that are *easier to read*  have lower lifetimes.
* Including *code samples* in your issue increases the chances of it getting fixed.
